services:
  laravel_app:
    container_name: laravel_app
    build:
      context: ./david_project
      dockerfile: dockerfile
    user: 1000:1000
    env_file:
      - "./david_project/.env"
    volumes:
      - ./david_project/:/var/www/
    ports:
      - "8000:8000"
    networks:
      - laravel_network
    depends_on:
      - db
      - fastapi

  db:
    image: mariadb:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:${DB_PORT}"
    volumes:
      - data:/var/lib/mysql
    networks:
      - laravel_network

  fastapi:
    container_name: fastapi
    build:
      context: ./python
      dockerfile : Dockerfile
              # si tu utilises un .env local pour config Python
    volumes:
      - ./python/:/app/
    ports:
      - "8001:8001"
    networks:
    - laravel_network





networks:
  laravel_network:

volumes:
  data: